### ISSUE TITLE
Merge this plug-in with LaClojure plug-in

### ISSUE THREAD

**Issue by aionescu-zz** [derkork/intellij-leiningen-plugin#29]
Please merge the LaClojure and the Lein plug-ins for IntelliJ into one, since it makes no sense to use the Lein plug-in without the laClojure one or the other way around.

http://youtrack.jetbrains.com/issue/CLJ-177

thank you.

**Comment by 256BitChris** [comment]
Your assumption that you can't use Clojure without Leiningen is incorrect.  You can use Clojure without Leiningen and many people do.  Also, the Leiningen IDEA plugin is maintained by non JetBrains people whereas the Clojure plugin is maintained by JetBrains.

This follows the same pattern as having Maven/Ant/Gradle each being a different plugin than the Java language itself.

**Comment by aionescu-zz** [comment]
> Your assumption that you can't use Clojure without Leiningen is incorrect. 

I see no point in using the Lein plug-in alone, without Clojure.

Many people forget about this plug-in however, and use only LaClojure: see the download numbers. All in one, they have an "incomplete Clojure experience" with IntelliJ due to fragmentation (or plug-ins being out of sync or missing integration of the two or whatever).

Considering how many features are missing (not even sure where to ask them), I'm not sure if this is the best strategy to have good Clojure support on IntelliJ.

> Also, the Leiningen IDEA plugin is maintained by non JetBrains people whereas the Clojure plugin is maintained by JetBrains.

So? Both are open source and on Github. Can't people with so much knowledge (average programmers can't really code plug-ins for the undocumented IntelliJ platform) work together for a far better user experience?

> This follows the same pattern as having Maven/Ant/Gradle each being a different plugin than the Java language itself.

Yeah, that's a "technical" view, but for the user they're all there when it starts, and they're very much integrated with each other: see the maven project management, dependency diagram, etc. - they are all strongly integrated with the project management functionality. Considering that project.clj (or other configs that will appear in the future) use the same language (unlike ANT/Maven that doesn't) this integration must be even more there.

Please don't get me wrong: I appreciate this plug-in very much, but for now (independent of what functionality in what part or plug-in is implemented), the overall Clojure experience in IDEs is quite primitive: not much more than a little highlighting :(.

Thank you.

**Comment by amanu** [comment]
+1

merge the two plug-ins and avoid duplicate work. the current state of clojure development in IDEs is quite poor: no wonder many use emacs.

regards.

**Comment by aadrian** [comment]
> Please merge the LaClojure and the Lein plug-ins for IntelliJ into one ..

Fully agree. The two plug-ins seem all the time out of sync, or now this one is not even available on recent IntelliJ releases :(  https://github.com/derkork/intellij-leiningen-plugin/issues/26

**Comment by ghost** [comment]
+1

**Comment by derkork** [comment]
The leiningen plugin focuses strongly on integrating the leiningen build system into IntelliJ. While Leiningen is primarily intended for building clojure projects it might evolve into a generic building tool over time (at least Leiningen 2 is a step in that direction, allowing to compile Java). So assuming it is a build system just like ant and maven for all of which exist separate plugins for IntelliJ, then it makes perfect sense to me to have the Leiningen plugin as separate plugin as well. It's about separation of concerns. 

I really fail to see why having two plugins is causing duplicate work. In fact both plugins have very little in common except the fact that they somehow interact with the Clojure language. The only duplicate work is maybe the release process which is actually just a few clicks. 

If the download numbers of LaClojure are larger than those of the Leiningen plugin, then maybe some people don't use Leiningen for building Clojure. If they are able to find the LaClojure plugin in the repo, I would assume they can find the Leiningen plugin as well (e.g. by simply typing Leiningen into the search field).

I agree that the plugin is not always up to date with the latest IntelliJ, but this is mostly due to the very limited amount of time that I have available for doing this. Everyone is welcome to participate in the development of this plugin, may it be by providing small patches or adding new functionality - that's why it is on GitHub. If you think this plugin is progressing too slow, you may be right, but you can help to change this - and you are very much invited to do so.

**Comment by aionescu-zz** [comment]
> While Leiningen is primarily intended for building clojure projects it might evolve into a generic building tool over time  ...

yeah, right :)

> So assuming it is a build system just like ant and maven for all of which exist separate plugins for IntelliJ, then it makes perfect sense to me to have the Leiningen plugin as separate plugin as well.

ANT and Maven are not really "separated" but from one hand, strongly synched with the rest. The integration between LaClojure and LeinIntelliJ is almost none: they don't even have each other as dependency. Considering that the Lein files _are_ Clojure files,  the interdependency should be even higher than that of Maven and ANT.

>  really fail to see why having two plugins is causing duplicate work. In fact both plugins have very little in common except the fact that they somehow interact with the Clojure language. 

There should be allot of things in common, mainly because project.clj is Clojure code, and also because Lein "enforces/suggests" best practices for structuring and managing Clojure projects, thus allowing an IDE to behave "smarter".

> Clojure. If they are able to find the LaClojure plugin in the repo, **I would assume** they can find the Leiningen plugin as well

yeah :). 

> Everyone is welcome to participate in the development of this plugin

I hear this allot. Unfortunately this is not realistic. IntelliJ plug-in development is the hardest skill ever.

**Comment by amanu** [comment]
> If they are able to find the LaClojure plugin in the repo, I would assume they can find the Leiningen plugin as well 

http://blog.tomeklipski.com/2013/04/running-and-debugging-clojure-code-with.html

regards.
