### ISSUE TITLE
Plugin incompatible with 12.1

### ISSUE THREAD

**Issue by fatlazycat** [derkork/intellij-leiningen-plugin#30]
Any easy fix ? Thanks

**Comment by ghost** [comment]
https://github.com/derkork/intellij-leiningen-plugin/pull/31 but it is just a quick fix.

**Comment by papachan** [comment]
Any fix. I cannot run any new poject in IntelliJ Idea.

**Comment by 256BitChris** [comment]
Just unpackage the jar and make the modifications from #31 to the .xml file then repackage it until the change gets to the plugin repository. 

Another fix is to use 12.0.4.

**Comment by papachan** [comment]
Nope. it didnt work for me. I ave unzipped the files, do the correction, and compressed it again into intellij. I have tried also to build the plugin but i didnt find how to import a plugin module.

**Comment by amanu** [comment]
@64BitChris 

> Another fix is to use 12.0.4.

I suppose this is a joke, right? :).
12.1 has a few major much required fixes (that plagued the entire new 12.x version as opposed to 11.x): http://www.jetbrains.com/idea/whatsnew/

After more than 10 years of (payed) IntelliJ use, I've never reverted from an official release to a previous one because of a plug-in (nor did any developer I know).

regards.

p.s. If this: http://youtrack.jetbrains.com/issue/CLJ-177 would have been done, the above problem would have not existed. Considering how small the Clojure and Lein community is, and from those how very very few can develop IntelliJ plug-ins, fragmentation is a very very bad thing.

**Comment by 256BitChris** [comment]
@amanu It's not a joke, it's a temporary work around until Jetbrains gets the plugin into its repository.  12.0.4 isn't unusable for Clojure development so it's a much better solution than not being able to open any project.

CLJ-177 isn't going to happen.  It's a violation of basic separation of concerns.  You're thinking very narrowly and short term with this.  If La Clojure and Leiningen plugins were merged then La Clojure wouldn't be able to be released without updating Leiningen - which is exactly what you want, but in reality it would just cause both plugins to be released more slowly. 

It'd be more constructive if you contributed to either project to fix the things you need so badly since we only have a couple people working on either La Clojure of this plugin, and its all done in our free time.  

@papachan - I think @derkork merged the changes in and so it's probably just waiting on Jetbrains to accept it and push it to the repository.  As far as importing a plugin module, you just put the plugin jar into the plugins directory and it will be loaded when IntelliJ restarts.

**Comment by derkork** [comment]
0.3.3 is now available in the repo.
