### ISSUE TITLE
[req] List/Document the implemented features so far.

### ISSUE THREAD

**Issue by aadrian** [derkork/intellij-leiningen-plugin#33]
Please list/document the features that are implemented so far in this plug-in.

Thanks in advance.

**Comment by 256BitChris** [comment]
Is there something you're looking for that isn't in the CHANGES file or the plugin history?

**Comment by amanu** [comment]
> Please list/document the features that are implemented so far in this plug-in.

+1

> Is there something you're looking for that isn't in the CHANGES file or the plugin history?

it's not clear what really this plug-in does (or is supposed to do) feature-wise until this version. 
a simple and clean feature list would be two fold usable:
- for new users to see exactly right away what the plug-in does. Nice example: http://handyedit.com/handytapestry.html
- for existing users to know when some behavior it's a bug and when it's something not implemented yet. Because this runs in IntelliJ, users expect lot of functionality and the frustration is quite big when almost nothing work. Having a clear feature list would clarify many things.

regards.

**Comment by derkork** [comment]
Kinda makes sense to me. I'll update the README.
