### ISSUE TITLE
Opening project fails on intelliJ 13 Community edition EAP

### ISSUE THREAD

**Issue by PragTob** [derkork/intellij-leiningen-plugin#43]
Importing/opening a project fails for me on intelliJ IDEA 13 with the error message: `createComponent() returns null for: class com.intellij.execution.RunManager`. More specifically for the [clojure-koans](https://github.com/functional-koans/clojure-koans).

**Comment by mping** [comment]
Same here.

**Comment by eebbesen** [comment]
I'm getting this same error using intelliJ 13 CE, but using intellij12 CE it appears to work fine.

**Comment by jcai** [comment]
same here

**Comment by 256BitChris** [comment]
Most of the support for this has been taken over by the [Cursive Clojure](http://cursiveclojure.com/) team.  Their version of this plugin supports IDEA 13 quite well.

**Comment by PragTob** [comment]
Unfortunately cursive is a paid IDE. Would love for them to contribute their changes back to this plugin - or well fork and open source that part... you know - be a good OSS citizen.

**Comment by theBlackDragon** [comment]
There doesn't seem to be a license on this project. Ianal but it seems to me me that building on this code could be potentially risky ( see: https://help.github.com/articles/open-source-licensing ), which would be a shame for sure.

**Comment by 256BitChris** [comment]
The author of Cursive Clojure obtained written permission from the original author, @derkork  to incorporate the code into his product.  He also has my permission for the code that I worked on, which is a large part of the Leiningen 2 support for this plugin.

There is no charge for Cursive while it's in the EAP phase and from my experience it's miles ahead of the La Clojure plugin and would be worth a reasonable license fee to use.

The two major contributors to this project, myself and Jan, aren't actively supporting this project anymore.  You can always submit pull requests if you want to spend the time to add features that already exist in Cursive Clojure.

**Comment by theBlackDragon** [comment]
I'm sorry if I wasn't clear. I wasn't talking about Cursive, though obviously the same things apply. I was talking about this project, which does not have a license at all.

Which means (as the GitHub link points out) that default copyright laws apply. In other words, one is unable to do anything with the code (barring that which the GitHub TOS guarantee, which is very little and means being stuck to GitHub for eternity) without explicit permission of the author of that specific piece of code (either you @64BitChris , @derkork  or one of the 3 other contributors)

As such building on this code for an open source Leiningen plugin is probably a bad idea in the long run. 

Whether others agree is a different matter. Personally I think it's important to be aware of the legal status of a project before picking it up (which is why I went searching for a license in the first place, and why I wrote this).

**Comment by derkork** [comment]
If it helps anyone, I have no issues adding a LICENSE.txt to this.

**Comment by 256BitChris** [comment]
@theBlackDragon - apologies for totally misunderstanding.  You are correct, we should put an official LICENSE file on the code for all the reasons you mentioned.

**Comment by derkork** [comment]
@64BitChris would the MIT license (http://opensource.org/licenses/MIT) 
be ok with you?

**Comment by 256BitChris** [comment]
@derkork - sounds good to me!
