### ISSUE TITLE
Add support for the "lein run" task

### ISSUE THREAD

**Issue by derkork** [derkork/intellij-leiningen-plugin#6]
Adding support for the lein run task would be nice. When clicking "lein run" it could ask for the parameters in some dialog (or one could use a set of parameters as default).  The defined run aliases could be listed as sub nodes of the run tasks so they could be executed with a single click.

**Comment by quephird** [comment]
I don't know if this is a configuration thing, a bona fide bug, or just my stupidity, but setting up a config for "lein run" for a jetty based Clojure app, and then running it succeeds but clicking stop from within IntelliJ does not kill the underlying java process (at least on Windows 7). Am I doing something wrong?

**Comment by derkork** [comment]
I don't think that there's an error on your end unless your app spawns another process which is obviously not controllable by IntelliJ. I'll check the issue.

**Comment by quephird** [comment]
I just wanted to let you know that indeed my app is issuing a run-jetty command, with the port number derived from within the code. I'm building the app using lein uberjar with :main specified in its project.clj. (I did it this way because that's how all the examples do it for running locally as well as deploying to Heroku.) So, you're right... my bad.

I guess what I need to figure out now is how to build a war file instead and figure out to externalize the server configuration, including the port number.

**Comment by derkork** [comment]
Thanks for letting me know. I close this issue then.
